name: CI checks

on:
  push:
  pull_request:

jobs:
  assemble:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run :assemble task
        run: ./gradlew assemble

  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run :check task
        run: ./gradlew check --continue

      - name: Merge SARIF reports
        # Necessary because upload-sarif only takes up to 15 SARIF files and we have more
        run: ./gradlew :mergeSarifReports
        if: ${{ always() }}

      - uses: github/codeql-action/upload-sarif@v2
        if: ${{ always() }}
        with:
          sarif_file: ${{ github.workspace }}/build/reports/static-analysis.sarif
          checkout_path: ${{ github.workspace }}

      - name: Upload reports for manual analysis
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Static analysis SARIF reports
          path: ${{ github.workspace }}/build/reports/*.sarif
          retention-days: 7
          if-no-files-found: error
