name: IJ Platform version updates

on:
  workflow_dispatch:
  schedule:
    - cron: 0 8 * * *

jobs:
  check-ij-platform-updates:
    name: Check for IJP updates
    runs-on: ubuntu-latest

    strategy:
      matrix:
        supported-ij-version:
          - 232
          - 233

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          cache: gradle
      - name: Setup Gradle
        run: chmod +x gradlew
      - name: Run Gradle
        run: ./gradlew checkLatestIntelliJPlatformBuild -Psupported.ij.version=${{ matrix.supported-ij-version }}
