name: Publish artifacts in Space

on:
  release:
    types: [ published ]
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  publish-current:
    name: Publish standalone & current-IJP-version bridge
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: Setup Gradle
        run: chmod +x gradlew

      - name: Run Gradle
        run: ./gradlew publishMainPublicationToSpaceRepository
        env:
          MAVEN_SPACE_USERNAME: ${{secrets.MAVEN_SPACE_USERNAME}}
          MAVEN_SPACE_PASSWORD: ${{secrets.MAVEN_SPACE_PASSWORD}}

  publish-older:
    name: Publish older-IJP-version bridge(s)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch-name:
          - releases/232
          - releases/233

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch-name }}

      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: Setup Gradle
        run: chmod +x gradlew

      - name: Run Gradle
        run: ./gradlew :ide-laf-bridge:publishMainPublicationToSpaceRepository
        env:
          MAVEN_SPACE_USERNAME: ${{secrets.MAVEN_SPACE_USERNAME}}
          MAVEN_SPACE_PASSWORD: ${{secrets.MAVEN_SPACE_PASSWORD}}
