name: Publish artifacts in Space
on:
  release:
    types: [ published ]
  push:
    branches: [ main ]
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    strategy:
      matrix:
        supported-ij-version:
          - 232
#          - 233

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        run: chmod +x gradlew
      - name: Run Jewel Core Publishing
        # supported.ij.version is needed here for project configuration and won't be used during publishing
        run: ./gradlew publishMainPublicationsToSpaceRepository -Psupported.ij.version=${{ matrix.supported-ij-version }}
        env:
          MAVEN_SPACE_USERNAME: ${{secrets.MAVEN_SPACE_USERNAME}}
          MAVEN_SPACE_PASSWORD: ${{secrets.MAVEN_SPACE_PASSWORD}}
      - name: Run Jewel IDE Publishing
        run: ./gradlew publishIdeMainPublicationsToSpaceRepository -Psupported.ij.version=${{ matrix.supported-ij-version }}
        env:
          MAVEN_SPACE_USERNAME: ${{secrets.MAVEN_SPACE_USERNAME}}
          MAVEN_SPACE_PASSWORD: ${{secrets.MAVEN_SPACE_PASSWORD}}
